#!/bin/sh

run() {
	if ! pgrep -f "$1" ; then
		"$@"&
	fi
}

run /usr/bin/prime-offload
run picom --config ~/.config/picom/picom.conf
run xsettingsd
run nm-applet
run /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
run xrdb merge ~/.Xresources
run ibus-daemon -drx
run blueberry-tray
run xfce4-power-manager --daemon
xrandr --output DisplayPort-0 --off --output DisplayPort-1 --primary --mode 1920x1080 --pos 1920x1080 --rotate normal --output DisplayPort-2 --mode 1920x1080 --pos 0x1080 --rotate normal --output HDMI-A-0 --mode 1920x1080 --pos 1920x0 --rotate normal --output DVI-D-0 --off